Repository 2011-team-phantom/phantom, pull requests merged in 2021-02, with the labels that each got.

#15 FEATURE: User login and connecting to plaid
  client/Routes.js
  client/app.js
  client/components/Login.js
  client/history.js
  client/index.js
  client/store/index.js
  client/store/user.js
  package-lock.json
  package.json
  server/auth/index.js
Labels: enhancement

#18 Created transfer store
  client/components/Budget.js
  client/components/LinkPlaid.js
  client/store/index.js
  client/store/transactions.js
  server/index.js
Labels: enhancement

#19 FEATURE: User's spending categories page
  client/Routes.js
  client/components/Budget.js
  client/components/LinkPlaid.js
Labels: enhancement

#22 added budget prop to database
  client/Routes.js
  client/components/AddBudget.js
  client/components/Budget.js
  client/components/Navbar.js
  client/components/Signup.js
  client/store/transactions.js
  server/api/index.js
  server/db/models/users.js
Labels: enhancement

#25 FEATURE: User can update their budget goals
  client/components/Budget.js
  client/store/transactions.js
  server/api/index.js
Labels: enhancement

#30 chore: rearranging routes for a logged in user
  client/Routes.js
  client/components/Login.js
  client/components/Navbar.js
  client/components/Transactions.js
  client/store/user.js
  server/index.js
Labels: enhancement

#44 STYLING: addbudget, login, signup
  client/components/AddBudget.js
  client/components/Glance.js
  client/components/LinkPlaid.js
  client/components/Login.js
  client/components/Navbar.js
  client/components/Signup.js
  client/components/Transactions.js
  public/bundle.js.LICENSE.txt
  public/style.css
Labels: enhancement

#46 STYLING: Budget page
  client/components/Budget.js
  client/store/transactions.js
  public/style.css
  server/api/index.js
Labels: enhancement

#54 STYLING: Budget page uses financial decimal point and shows percentage progress bar
  client/components/Budget.js
  public/style.css
Labels: enhancement

#63 BUG: User can input addBudget total
  client/components/AddBudget.js
Labels: bug

#66 bug: fixed signup transaction pull
  client/components/AddBudget.js
  client/components/LinkPlaid.js
  client/components/Signup.js
  client/components/Transactions.js
  client/store/transactions.js
  server/index.js
Labels: bug

#73 BUG: Form validations on login, signup, and addbudget
  client/components/AddBudget.js
  client/components/Login.js
  client/components/Signup.js
  client/store/user.js
  package-lock.json
  package.json
  server/auth/index.js
Labels: bug, enhancement

#84 FEATURE: User can filter between 3, 6, 12 months view on transactions page
  client/components/Budget.js
  client/components/Transactions.js
  package-lock.json
  package.json
  server/index.js
Labels: enhancement

#91 Added Budget recommendations
  .DS_Store
  client/components/AddBudget.js
  client/components/Animation.js
  client/components/Footer.js
  client/components/Login.js
  client/components/Signup.js
  client/store/transactions.js
  package-lock.json
  package.json
  public/src/.DS_Store
  public/src/41477-save-piggy-bank.json
  server/api/index.js
  server/auth/index.js
  server/db/models/users.js
Labels: enhancement

#92 fixed addition bug
  client/components/AddBudget.js
  client/components/EditUser.js
  client/store/transactions.js
Labels: bug, enhancement

#93 FEATURE: User can add manual transactions
  client/components/AddTransaction.js
  client/components/Transactions.js
  client/store/transactions.js
  public/style.css
  server/api/index.js
  server/db/models/users.js
  server/index.js
Labels: enhancement

#98 profile page updates
  .DS_Store
  client/components/Budget.js
  client/components/CoinAnimation.js
  client/components/EditUser.js
  client/components/Login.js
  client/components/PigAnimation.js
  client/components/ProfileAnimation.js
  public/.DS_Store
  public/src/.DS_Store
  public/src/44076-dollar.json
  public/src/5055-latest-mobile-plus-website-savings.json
  public/style.css
Labels: enhancement

#100 FIX: Error message on login and signup page
  client/components/Login.js
  client/components/Signup.js
  client/store/user.js
Labels: bug

#103 FEATURE: User cannot input a budget amount greater than their monthly income
  client/components/AddBudget.js
Labels: enhancement

#104 Documentation: Added .env.example file
  .env.example
Labels: documentation

#107 added saving to budget page
  .babelrc
  client/components/Budget.js
  client/components/EditUser.js
  client/components/Footer.js
  client/components/Navbar.js
  package-lock.json
  package.json
  public/src/profileman.png
  public/style.css
Labels: enhancement

#108 Documentation: Updated Readme
  README.md
Labels: documentation

#112 removed decimals for savings card
  client/components/Budget.js
Labels: bug
